### ISSUE TITLE
site_url error when we submit on OSTI test server

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-doi-service#168]
See email thread:
Hi Guys,
 
I’ve attached the input label that I originally submitted to the OSTI test server, as well as a screenshot of the corresponding entry on the IAD test site. Note that the input label is in JSON format, since we recently added that as a valid format for a release request. I will try again with XML format to see if that makes any difference.
 
Scott
 
From: "Loubrieu, Thomas G (US 398F)" <thomas.g.loubrieu@jpl.nasa.gov>
Date: Wednesday, March 17, 2021 at 9:30 AM
To: "Joyner, Ronald (US 398G)" <ronald.joyner@jpl.nasa.gov>, "Collins, Scott (US 398F)" <scott.collins@jpl.nasa.gov>
Subject: Re: OSTI error on site_url
 
Hi Ron, Scott
 
Thanks for your feedback Ron.
 
Scott can you provide Ron with the OSTI record on submission of which the error was raised ?
 
Can you also check that the DOI value is valid (ie exists), since Ron mentions it is lacking numbers in the suffix.
 
Thanks,
 
Thomas
 
From: "Joyner, Ronald (US 398G)" <ronald.joyner@jpl.nasa.gov>
Date: Wednesday, March 17, 2021 at 8:02 AM
To: "Loubrieu, Thomas G (US 398F)" <thomas.g.loubrieu@jpl.nasa.gov>
Subject: RE: OSTI error on site_url
 
 
Howdy,
 
>> uid":"10.17189/29348
 
The suffix part appears to be lacking some numbers ?  All of the minted DOIs have a suffix of 7 chars ?
 
RJ
 
 
From: Loubrieu, Thomas G (US 398F) 
Sent: Tuesday, March 16, 2021 3:07 PM
To: Joyner, Ronald (US 398G) <ronald.joyner@jpl.nasa.gov>
Cc: Collins, Scott (US 398F) <scott.collins@jpl.nasa.gov>; Padams, Jordan H (US 398A) <jordan.h.padams@jpl.nasa.gov>
Subject: OSTI error on site_url
 
Hi Ron,
 
Scott who is maintaining/devlopping the DOI service Qui used to work on had an error with the OSTI submission. We would like to have your advice on that and possibly report to OSTI if needed.
 
When Scott submit a DOI to OSTI he’s getting this error back from them:
Registration update failed: {"errors":[{"source":"url","uid":"10.17189/29348","title":"URL https://pds.nasa.gov/ds-view/pds/viewBundle.jsp?identifier=urn%3Anasa%3Apds%3Ainsight_cameras&version=1.0 is not allowed by repository osti.nasapds domain settings."}]}
 
 
Scott will be able to provide you with more details if needed (maybe the full OSTI record which was submitted).
 
Thanks,
 
Thomas

**Comment by tloubrieu-jpl** [comment]
We're waiting for Ron's feedback or Ron to contact OSTI support on that

**Comment by tloubrieu-jpl** [comment]
Ron said, that should work now. @collinss-jpl  need to check again.

**Comment by tloubrieu-jpl** [comment]
@collinss-jpl have you had a chance to test that ? Thanks

**Comment by collinss-jpl** [comment]
@tloubrieu-jpl Sorry for the delay, just took some time to revisit this and was able to complete a test reserve-and-release without getting the site url error, so from my end the issue seems to be resolved. 

I noticed that Ron made a change to the site url he used for his submission, so for my test I reused the same site url to see if I could trigger the previous error (my hunch was the error was related to URL reuse between DOI's), but this did not occur. Based on that, I'm ready to say this issue is resolved (until it isn't 🤣)

**Comment by collinss-jpl** [comment]
After taking some more time to look into this, I determined that the core service has not been handling HTML escaping of ampersands (&) correctly. This is more likely the root cause for why OSTI provided an error for that particular DOI submission. I will be pushing up a fix for the issue later today.

**Comment by tloubrieu-jpl** [comment]
Thanks @collinss-jpl . That sounds good.
