### ISSUE TITLE
Develop DOI metadata automated validation component

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-doi-service#18]
Validation of the DOI metadata will most likely involve some curation from PDS personnel, however, there are some way we could potentially validate specific values entered. We could check these individually, use something like Schematron to validate.

Below is Schematron we can look through for reference submitted from one our discipline node colleagues.

[SBN-DataCite.sch.txt](https://github.com/NASA-PDS-Incubator/pds-doi-service/files/4463734/SBN-DataCite.sch.txt) (rename to .sch)

**Applicable requirements**
:unicorn: #12
:unicorn: #13

**Comment by tloubrieu-jpl** [comment]
Raise:
- error if "creator" is missing
- warning if "editor" is missing

**Comment by tloubrieu-jpl** [comment]
When something goes wrong with the OSTI server (unexpected response), the service should to 2 things:
- send the message to the user sayings something unexpected happened
- an email must be sent to  pds-operator@jpl.nasa.gov with all useful information (data submitted, error message, user...)

**Comment by tloubrieu-jpl** [comment]
Qui started the schematron.
Some weird behavior need to discuss.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl we should maybe ask if Ron would be willing to create a schematron for us. he has a ton of experience and could probably do it in no time

**Comment by tloubrieu-jpl** [comment]
I asked Ron to look at the schematron. Actually the strange behaviour was what we have discussed last week and was unrelated to schematron but related to OSTI submission This is solved now.

**Comment by tloubrieu-jpl** [comment]
@Qui the remaining task here is to check that a title has not already been used in the sqllite database, for the latest records which have a different lid.

You can have that in the OSTI validator object.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl do we already check the PDS4 LIDVID has not already been used in the database? that is another potential way to check this.

**Comment by tloubrieu-jpl** [comment]
@jordanpadams you can review if the rule translate correctly what we want.

@qchaupds  based on branch doi_entity  you can create a #18 branch and to the following implementation:

You will create a DOIValidator object which will have a method 'validate',  which will take as argument a DOI object and the action value.

The object will also have a workflow_order dictionary attribute:
{'reserved_not_submitted':0
'reserved':1,
'draft':2,
'pending':3
'registered': 4}

Validate method will do:
- **check title**: there is no DOI in sqllite database which has the same "title" but different "lid". 

When rule is not valid it will raise a InvalidDOIException

The error message will be:
The title "<title>" has already been used for a DOI by lidvid: <lidvid>, status: <status>, doi: <doi>. You must use a different title.

When rule is not valid it will raise a InvalidDOIException

- **check lidvid update**:  if DOI does not have a doi field, and action step is 'release' there is no DOI in sqllite database with the same lidvid and a DOI attributed.

When the rule is not valid is will raise a IllegalDOIActionException

The error message will be:
There is already a DOI <doi value in database> submitted for this lidvid <lidvid> (status=<status value>). You can not submit a new DOI for the same lidvid.

- **check workflow": there is not record in the sqllite database with same lidvid but a higher status than the current action (see workflow_order)

When the rule is not valid it will raise a UnexpectedDOIActionException

The error message will be:
There is a DOI record which status is "status". Are you sure you want to restart the workflow from step "<current action>" for the lidvid <livvid value>.

If flag --force is set. the exception UnexpectedDOIActionException will be ignored. 
Otherwise, the exceptions will trigger the leave immediate of the process with no action (no transaction written, no record submitted to OSTI).

The validation will be applied in the 'reserve', 'draft' and 'release' actions.

**Comment by tloubrieu-jpl** [comment]
A merge request should be ready for end of the week.

@qchaupds  has a question on the unit test management (tests datasets management).

**Comment by tloubrieu-jpl** [comment]
To validate the rule **check lidvid update A** we do 3 actions (and 2 unit tests):
- given: that record A has been released to OSTI
- then: update locally record A with new publisher
- then: submit record A (again) should FAIL
- then: submit record A with added DOI value should SUCCEED and publisher should be updated on OSTI side.
