### ISSUE TITLE
CI does not work on main branch for dev release

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-doi-service#220]
## 📜 To Reproduce
See action https://github.com/NASA-PDS/pds-doi-service/runs/2955493255?check_suite_focus=true

## 🕵️ Expected behavior

CI should work after the update #209 

## 🖥 System Info

---

** :unicorn: Applicable requirements**

**Comment by nutjob4life** [comment]
I don't think I have permission to fix this. The issue seems to be here:

![Screen Shot 2021-06-30 at 5 14 45 PM](https://user-images.githubusercontent.com/814813/124038953-a2eb9700-d9c7-11eb-9419-6ce8c5dddf2e.png)

The username `***` is the `PYPI_USERNAME` secret in the `NASA-PDS` organization, which I think is `pdsen-ci`.

But that user isn't a collaborator on the project:

![Screen Shot 2021-06-30 at 5 21 28 PM](https://user-images.githubusercontent.com/814813/124039027-beef3880-d9c7-11eb-973f-e5e32718a4f4.png)

If that makes sense, go ahead and remove me from the list of assignees. If not, comment below and we'll see what we can figure out.

**Comment by tloubrieu-jpl** [comment]
Hi @nutjob4life,

Thanks for your quick reply. I invited you to be an owner of this package on pypi before but you did not answer 😩 I re-invited you.

I am not finding pdsen-ci user on pypi test. Is it only available on the production pypi ?

**Comment by tloubrieu-jpl** [comment]
@collinss-jpl do you have a login to pypi (test and prod): https://test.pypi.org/ and pypi.org ?

I should add you as an owner of our python packages.

**Comment by nutjob4life** [comment]
Hmm, looks like it might not be on test.pypi.org:
 
![Screen Shot 2021-06-30 at 5 43 44 PM](https://user-images.githubusercontent.com/814813/124040580-c49a4d80-d9ca-11eb-99b3-1a1cd2c28c5a.png)

**Comment by collinss-jpl** [comment]
@tloubrieu-jpl I've create an account on test.pypi.org, username is collinss-jpl

**Comment by nutjob4life** [comment]
@collinss-jpl invitations sent from pypi.org and test.pypi.org ✓

**Comment by tloubrieu-jpl** [comment]
The CI works on dev versions now, see https://github.com/NASA-PDS/pds-doi-service/actions/runs/1054402430
