### ISSUE TITLE
DOI Batch Processing capability

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-doi-service#25]
**Applicable requirements**
:unicorn: #10
:unicorn: #6
:unicorn: #7
:unicorn: #8
:unicorn: #9

**Comment by tloubrieu-jpl** [comment]
(email from @jordanpadams )
Good question. I think for now, let's just handle two cases:

List or URLs to PDS4 labels
Upload / file system submission of a list of PDS4 labels

I think there may be other cases for mass update of DOI metadata, but I think for now, we can just handle those as one-off cases.

**Comment by tloubrieu-jpl** [comment]
@qchaupds you can work on these 2 cases which will be an extension of the current draft action which should accept as input:
- a list of url (instead of a single url). That will work with a ',' spearator as for the list action arguments.
- a directory where all the xml files will be considered as pds4 labels.

In the 2 cases, the action will produce a single output in OSTI format (records/record)

**Comment by tloubrieu-jpl** [comment]
Merged with pull request #54
