### ISSUE TITLE
Update default DOI metadata according to changes in requirements

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-doi-service#55]
- [ ] why does this title contain some funky date information there? We should just use the Bundle Title as-is (I checked the Insight label and this is not the title).
https://github.com/NASA-PDS/pds-doi-service/blob/61c593bce85c2b0bb4bd6e912339212f62031b11/input/DOI_Release_20200727_from_draft.xml#L4

- [ ] by default (for now), this should always be `Dataset`
https://github.com/NASA-PDS/pds-doi-service/blob/61c593bce85c2b0bb4bd6e912339212f62031b11/input/DOI_Release_20200727_from_draft.xml#L32

- [x] this should be defaulted to `NASA Planetary Data System`
https://github.com/NASA-PDS/pds-doi-service/blob/61c593bce85c2b0bb4bd6e912339212f62031b11/input/DOI_Release_20200727_from_draft.xml#L54

- [x] let's camel case this - `PDS Operator`
https://github.com/NASA-PDS/pds-doi-service/blob/61c593bce85c2b0bb4bd6e912339212f62031b11/input/DOI_Release_20200727_from_draft.xml#L55

- [ ] `product_type_specific` should use the following values:
    * PDS4 Product_Bundle - `PDS4 Refereed Data Bundle`
    * PDS4 Product_Collection - `PDS4 Refereed Data Collection`
https://github.com/NASA-PDS/pds-doi-service/blob/61c593bce85c2b0bb4bd6e912339212f62031b11/input/DOI_Release_20200727_from_draft.xml#L33

- [x] for the LIDVID related identifier:
    * `identifier_type` = `URN`
    * `relation_type` = `IsIdenticalTo`
https://github.com/NASA-PDS/pds-doi-service/blob/61c593bce85c2b0bb4bd6e912339212f62031b11/input/DOI_Release_20200727_from_draft.xml#L36

- [ ] is there a reason this `related_identifiers` block repeats?
https://github.com/NASA-PDS/pds-doi-service/blob/61c593bce85c2b0bb4bd6e912339212f62031b11/input/DOI_Release_20200727_from_draft.xml#L86

- [ ] check to see if this mandatory (test without it). if not, remove.
https://github.com/NASA-PDS/pds-doi-service/blob/3ce958942c3a97572eee3958622aceac1a141e39/config/DOI_template_20200407-mustache.xml#L5

**Comment by qchaupds** [comment]
1. funky date information 
    left over from test artifact checking to see if OSTI will accept updated metadata .  Will be correct next time.

2. product_type default
   will fix in the code.

3. availability,  operator, and product_type_specific tags
   will fix in the code

4. related_identifiers
   The pystache config file does indeed has repeating tags.  Will delete one of them.

5. creators
   Tag added by Thomas due to reaction from OSTI.  Will test again to see if they need it or not.

**Comment by qchaupds** [comment]
It is confirmed that the creators tag is not needed.  A successful submission of a draft DOI (no creators tag) on 08/10/2020 at 8:31 AM resulted in:

    <id>26622</id>
    <site_code>NASA-PDS</site_code>
    <title>InSight Cameras Bundle</title>
    <doi>10.17189/26622</doi>

The product_type value with value 'Bundle' was rejected by OSTI until it was modified to 'Dataset'.  The template should be changed to 'Dataset' as default regardless of what is in the PDS4 label.

**Comment by qchaupds** [comment]
It should also be noted that when the same label was drafted by developer, the code correctly throw an exception due to duplicate 'title' field until the --force flag was used (already in the database).

{pds-dev-el7.jpl.nasa.gov}/home/qchau/sandbox/pds-doi-service 142 % python3 pds_doi_core/cmd/pds_doi_cmd.py draft -n img -s Qui.T.Chau@jpl.nasa.gov -i input/bundle_in_with_contributors.xml

pds_doi_core.input.exeptions.DuplicatedTitleDOIException: The title: 'InSight Cameras Bundle' has already been used for a DOI by lidvid:urn:nasa:pds:insight_cameras::1.0, status: draft , doi: None. You must use a different title.
